/// Generated by `script/generate_package_swift`.
enum Package {
    static let version = ""
    static let installMethod = "unknown"
    static let gitOrigin = ""
    static let gitRevision = ""
    static let swiftVersion = "6.2.3 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)"
    static let swiftDriverVersion = "1.127.14.1"
}
